package com.anderscore.springbatch.article.domain;
// Generated 12.04.2010 14:29:28 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * AnotherEntity generated by hbm2java
 */
@Entity
public class AnotherEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7025532553132738753L;

	@Id
	@Column(nullable = false, precision = 10, scale = 0)
	private long id;

	@Column(nullable = false, precision = 2, scale = 0)
	private byte anotherIdentifier;

	@Column(precision = 8, scale = 0)
	private Integer integerField;

	public long getId() {
		return id;
	}

	public byte getAnotherIdentifier() {
		return anotherIdentifier;
	}

	public void setAnotherIdentifier(byte anotherIdentifier) {
		this.anotherIdentifier = anotherIdentifier;
	}

	public Integer getIntegerField() {
		return integerField;
	}

	public void setIntegerField(Integer integerField) {
		this.integerField = integerField;
	}
}
